- hosts: all
  tasks:
  - name: Install kubectl
    become: yes
    shell:  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl";\
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  
  - name: Install Docker
    become: yes
    shell:  curl -fsSL https://get.docker.com -o get-docker.sh; \
            sh get-docker.sh

  - name: install minikube
    become: yes
    shell:  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 ; \
            install minikube-linux-amd64 /usr/local/bin/minikube; \
            minikube start

remote_user: ubuntu
